# Load the Datasets

In [1]:
import glob
import cv2
import time

# Record the starting time
start_time = time.time()

images = [cv2.imread(file) for file in glob.glob("/home/t326h379/AffectNet-8Labels/train_set/train_set/images/*.jpg")]

# Record the end time
end_time = time.time()

# Calculate the elapsed time
elapsed_time = end_time - start_time

# Print or use the elapsed time as needed
print(f"Execution time: {elapsed_time} seconds")

import numpy as np

# Record the starting time
start_time = time.time()

train_images = np.array(images)

# Record the end time
end_time = time.time()

# Calculate the elapsed time
elapsed_time = end_time - start_time

# Print or use the elapsed time as needed
print(f"Execution time: {elapsed_time} seconds")

globe_loaded_images = [file.split("/")[-1] for file in glob.glob("/home/t326h379/AffectNet-8Labels/train_set/train_set/images/*.jpg")]

import glob
import os
os.chdir('/home/t326h379/AffectNet-8Labels/train_set/train_set/annotations/')
training_exp_file_count =[]
for name in glob.glob('*.npy'):
    a = name.split("_")
    if a[1].startswith("exp"):
        training_exp_file_count.append(name)
        
annotation_files_number_training = set()
for i in range(len(training_exp_file_count)):
    train_exp = training_exp_file_count[i].split("_")
    annotation_files_number_training.add(train_exp[0])
    
import pickle
with open('Kritika_AffectNet_Training.pickle', 'rb') as handle:
    b = pickle.load(handle)
    
y_train = []
for i in range(len(globe_loaded_images)):
    y_train.append(int(b[globe_loaded_images[i].split(".")[0]]))
    
y_train = np.array(y_train)

from tensorflow.keras.utils import to_categorical
# One-hot encode the target labels
num_classes = 8  # Replace with the actual number of classes
y_train_one_hot = to_categorical(y_train, num_classes)

Execution time: 3899.7596004009247 seconds
Execution time: 35.250779151916504 seconds


In [2]:
import tensorflow as tf
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense, MaxPooling2D, Conv2D, Flatten, \
    BatchNormalization, Activation, GlobalAveragePooling2D, DepthwiseConv2D, \
    Dropout, ReLU, Concatenate, Input, add, Conv1D, MaxPooling1D
from tensorflow.keras.callbacks import EarlyStopping
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets

In [3]:
X_train, X_test, y_train, y_test = train_test_split(train_images, y_train_one_hot, stratify= y_train, test_size=0.1, random_state=42)

# Convert the Whole Training image to 32-bit floating-point format

In [4]:
X_train_float32 = X_train.astype(np.float32) / 255.0

In [5]:
print(X_train_float32.shape, y_train.shape)

(258885, 224, 224, 3) (258885, 8)


# Stacked Generlaization to increase the predicitive performance

In [6]:
import tensorflow as tf
from tensorflow.keras.utils import to_categorical
import pandas as pd
from Bio import SeqIO
import os
import random
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv1D, Dense, MaxPooling1D, Input, Flatten, LSTM, Dropout, Bidirectional, LeakyReLU, Reshape, Lambda
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import plot_model
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras.callbacks import EarlyStopping
# performance matrices
from sklearn.metrics import confusion_matrix, matthews_corrcoef, accuracy_score
# plots
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.callbacks import ModelCheckpoint
from numpy import array
from numpy import argmax
from tensorflow.keras.regularizers import l1, l2
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Concatenate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_curve, roc_auc_score, classification_report, auc
import imblearn
from imblearn.under_sampling import RandomUnderSampler
from tensorflow.keras.models import load_model
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam, SGD
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.metrics import roc_curve, auc, roc_auc_score,matthews_corrcoef
from tensorflow.keras.callbacks import Callback,EarlyStopping
import random
from tensorflow.keras.layers import *
from tensorflow.keras import backend as K
import os
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, recall_score, matthews_corrcoef, roc_curve, auc
from tensorflow.keras import backend as K
import itertools
import os
import random
import tensorflow
import tensorflow as tf
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from sklearn import metrics
from sklearn import preprocessing
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.layers import Dense, Activation, Flatten, Dropout, Reshape
from tensorflow.keras.layers import Conv1D,Conv2D, MaxPooling2D
from tensorflow.keras.models import Sequential,Model
from tensorflow.keras import utils
from tensorflow.keras import optimizers
from tensorflow.keras.optimizers import Adam,SGD
from tensorflow.keras.regularizers import l2
import copy
from sklearn.metrics import roc_auc_score
from Bio import SeqIO
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, Reshape, Lambda, LSTM
from tensorflow.keras.layers import Conv1D, MaxPooling1D
from tensorflow.keras.layers import Bidirectional, TimeDistributed
from tensorflow.keras.callbacks import ModelCheckpoint,ReduceLROnPlateau
from numpy import array
from numpy import argmax
from sklearn.model_selection import train_test_split
from imblearn.under_sampling import RandomUnderSampler
from sklearn.utils import shuffle
from tensorflow.keras import backend as K
from tensorflow.keras.backend import expand_dims
import matplotlib.pyplot as plt
from tensorflow.keras.regularizers import l1, l2
from sklearn.metrics import roc_curve, auc, classification_report
from tensorflow.keras.models import load_model
import pandas as pd
from tensorflow.keras.layers import Conv1D,Conv2D, MaxPooling2D,GlobalMaxPooling1D
from Bio import SeqIO
import random
import functools
import itertools
import os
import random
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from sklearn import metrics
from sklearn import preprocessing
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from tensorflow.keras.layers import Dense, Activation, Flatten, Dropout, Reshape, BatchNormalization
from tensorflow.keras.layers import Conv1D, Conv2D, MaxPooling2D
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras import optimizers
from tensorflow.keras.optimizers import Adam, SGD
from tensorflow.keras.regularizers import l2
import copy
from sklearn.metrics import confusion_matrix
from sklearn.metrics import matthews_corrcoef
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score, recall_score
from tensorflow.keras import models,layers,optimizers,regularizers
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam, SGD
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.metrics import roc_curve, auc, roc_auc_score,matthews_corrcoef
from tensorflow.keras.callbacks import Callback,EarlyStopping
import random
from tensorflow.keras.layers import *
from tensorflow.keras import backend as K
import os
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, recall_score, matthews_corrcoef, roc_curve, auc
from tensorflow.keras import backend as K
import itertools
import os
import random
import tensorflow
import tensorflow as tf
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from sklearn import metrics
from sklearn import preprocessing
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.layers import Dense, Activation, Flatten, Dropout, Reshape
from tensorflow.keras.layers import Conv1D,Conv2D, MaxPooling2D
from tensorflow.keras.models import Sequential,Model
from tensorflow.keras import utils
from tensorflow.keras import optimizers
from tensorflow.keras.optimizers import Adam,SGD
from tensorflow.keras.regularizers import l2
import copy
from sklearn.metrics import roc_auc_score
from Bio import SeqIO
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, Reshape, Lambda, LSTM
from tensorflow.keras.layers import Conv1D, MaxPooling1D
from tensorflow.keras.layers import Bidirectional, TimeDistributed
from tensorflow.keras.callbacks import ModelCheckpoint,ReduceLROnPlateau
from numpy import array
from numpy import argmax
from sklearn.model_selection import train_test_split
from imblearn.under_sampling import RandomUnderSampler
from sklearn.utils import shuffle
from tensorflow.keras import backend as K
from tensorflow.keras.backend import expand_dims
import matplotlib.pyplot as plt
from tensorflow.keras.regularizers import l1, l2
from sklearn.metrics import roc_curve, auc, classification_report
from tensorflow.keras.models import load_model
import pandas as pd
from tensorflow.keras.layers import Conv1D,Conv2D, MaxPooling2D,GlobalMaxPooling1D
from Bio import SeqIO
import random
import functools
import itertools
import os
import random
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from sklearn import metrics
from sklearn import preprocessing
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from tensorflow.keras.layers import Dense, Activation, Flatten, Dropout, Reshape, BatchNormalization
from tensorflow.keras.layers import Conv1D, Conv2D, MaxPooling2D
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras import optimizers
from tensorflow.keras.optimizers import Adam, SGD
from tensorflow.keras.regularizers import l2
import copy
import pandas as pd
from tensorflow.keras.utils import plot_model
import numpy as np
import os

In [7]:
import os
os.chdir('/home/t326h379/AffectNet-8Labels/train_set/train_set/annotations/')
import tensorflow as tf
import matplotlib.pyplot as plt

In [8]:
import tensorflow as tf
saved_model_vit = tf.keras.models.load_model('saved_model_vit')

In [9]:
saved_model_vit.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
permute (Permute)            (None, 3, 224, 224)       0         
_________________________________________________________________
vit (Custom>TFViTMainLayer)  {'last_hidden_state': (No 86389248  
_________________________________________________________________
tf_op_layer_strided_slice (T (None, 768)               0         
_________________________________________________________________
Dense_First_Layer (Dense)    (None, 128)               98432     
_________________________________________________________________
dropout_74 (Dropout)         (None, 128)               0         
_________________________________________________________________
Classification_Layer (Dense) (None, 8)                

In [10]:
import tensorflow as tf
os.chdir('/home/t326h379/AffectNet-8Labels/val_set/annotations/')
saved_model_vgg = tf.keras.models.load_model('VGG19_finetune.h5')

In [11]:
saved_model_vgg.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)      

In [31]:
%matplotlib inline
def define_stacked_model(members):
        # update all layers in all models to not be trainable
    for i in range(len(members)):
        model = members[i]
        for layer in model.layers:
            # make not trainable
            layer.trainable = False
            # rename to avoid 'unique layer name' issue
            layer._name = 'ensemble_' + str(i+1) + '_' + layer._name
    # define multi-headed input
    ensemble_visible = [model.input for model in members]
    # concatenate merge output from each model
    ensemble_outputs = [model.output for model in members]
    merge = concatenate(ensemble_outputs)
    hidden = Dense(16, activation='relu')(merge)
    output = Dense(8, activation='softmax')(hidden)
    model = Model(inputs=ensemble_visible, outputs=output)
    # plot graph of ensemble
#     plot_model(model, show_shapes=True, to_file='model_graph.png')
    # compile
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

def fit_stacked_model(model, inputX, inputy):
    # prepare input data
    X = inputX
    # encode output data
    inputy_enc = inputy
    # fit model
    model.fit(X, inputy_enc, epochs=10, verbose=1) 
    model.save("Stacked_Generalization_ViT_and_VGG_with_10_Epoch.h5")
   
def predict_stacked_model(model, inputX):
    # prepare input data
    X = inputX
    # make prediction
    return model.predict(X, verbose=0)

In [32]:
print(X_train_float32.shape, y_train.shape)

(258885, 224, 224, 3) (258885, 8)


In [33]:
train_input_X = [X_train_float32,X_train_float32]


n_members = 2
members = [saved_model_vit,saved_model_vgg]
print('Loaded %d models' % len(members))

stacked_model = define_stacked_model(members)

Loaded 2 models


# Train the Stacked Model

In [34]:
fit_stacked_model(stacked_model, train_input_X, y_train)

Epoch 1/10
8091/8091 [==============================] - 18366s 2s/step - loss: 0.2495 - accuracy: 0.9379
Epoch 2/10
8091/8091 [==============================] - 18873s 2s/step - loss: 0.2011 - accuracy: 0.9481
Epoch 3/10
8091/8091 [==============================] - 18816s 2s/step - loss: 0.1988 - accuracy: 0.9482
Epoch 4/10
4539/8091 [===============>..............] - ETA: 2:17:24 - loss: 0.1960 - accuracy: 0.9488

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



8091/8091 [==============================] - 18782s 2s/step - loss: 0.1978 - accuracy: 0.9485
Epoch 5/10
8091/8091 [==============================] - 18740s 2s/step - loss: 0.1973 - accuracy: 0.9485
Epoch 6/10
8091/8091 [==============================] - 18754s 2s/step - loss: 0.1963 - accuracy: 0.9487
Epoch 7/10
8091/8091 [==============================] - 18718s 2s/step - loss: 0.1956 - accuracy: 0.9485
Epoch 8/10
8091/8091 [==============================] - 18804s 2s/step - loss: 0.1951 - accuracy: 0.9485
Epoch 9/10
1835/8091 [=====>........................] - ETA: 4:01:28 - loss: 0.1965 - accuracy: 0.9486

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



8091/8091 [==============================] - 18694s 2s/step - loss: 0.1949 - accuracy: 0.9481
Epoch 10/10
8091/8091 [==============================] - 19815s 2s/step - loss: 0.1942 - accuracy: 0.9486


In [37]:
stacked_model.summary()

Model: "functional_3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
ensemble_2_ensemble_2_input_1 ( [(None, 224, 224, 3) 0                                            
__________________________________________________________________________________________________
ensemble_2_ensemble_2_block1_co (None, 224, 224, 64) 1792        ensemble_2_ensemble_2_input_1[0][
__________________________________________________________________________________________________
ensemble_2_ensemble_2_block1_co (None, 224, 224, 64) 36928       ensemble_2_ensemble_2_block1_conv
__________________________________________________________________________________________________
ensemble_2_ensemble_2_block1_po (None, 112, 112, 64) 0           ensemble_2_ensemble_2_block1_conv
_______________________________________________________________________________________

# Results after 10 epochs of meta classifier training

In [36]:
print(X_test_Independent_float32.shape, y_test_without_one_hot.shape)

(28766, 224, 224, 3) (28766,)


In [38]:
y_pred_stack = stacked_model.predict([X_test_Independent_float32,X_test_Independent_float32])

In [39]:
y_pred_stack_without_one_hot = np.argmax(y_pred_stack, axis=1)

In [40]:
y_pred_stack_without_one_hot

array([1, 0, 1, ..., 1, 6, 4])

In [41]:
from sklearn.metrics import matthews_corrcoef
from sklearn.metrics import confusion_matrix
from sklearn.metrics import *

In [42]:
print("Confusion Matrix : \n",confusion_matrix(y_test_without_one_hot, y_pred_stack_without_one_hot))
print("Accuracy on test set:   ",accuracy_score(y_test_without_one_hot,y_pred_stack_without_one_hot))

Confusion Matrix : 
 [[ 5307   827   490   263    49    31   442    79]
 [  852 12138    56   152    15    25    80   124]
 [  721    79  1429    56    59    15   183     4]
 [  330   207    44   689    99     1    31     8]
 [   60    33    73   142   268    11    51     0]
 [   55    45    47     7    13   127    85     1]
 [  638    75   153    42    49    62  1455    14]
 [  104   191     9     3     1     5    17    45]]
Accuracy on test set:    0.745950079955503


# Load the below model

In [43]:
stacked_model.save("Stacked_Generalization_Meta_Trained_For_10_Epoch_Final_Stacked_Generalization_ViT_and_VGG_.h5")

# See the predicitive performace on the independent test dataset through Stacked Model

In [16]:
X_test_Independent_float32 = X_test.astype(np.float32) / 255.0

In [17]:
stacked_model

In [18]:
X_test_Independent_float32.shape

(28766, 224, 224, 3)

In [19]:
y_test_without_one_hot =  np.argmax(y_test, axis=1)

In [20]:
y_pred_stack = stacked_model.predict([X_test_Independent_float32,X_test_Independent_float32])

In [22]:
y_pred_stack_without_one_hot = np.argmax(y_pred_stack, axis=1)

In [23]:
y_pred_stack_without_one_hot

array([1, 0, 1, ..., 1, 6, 4])

In [24]:
from sklearn.metrics import matthews_corrcoef
from sklearn.metrics import confusion_matrix
from sklearn.metrics import *

In [25]:
print("Confusion Matrix : \n",confusion_matrix(y_test_without_one_hot, y_pred_stack_without_one_hot))
print("Accuracy on test set:   ",accuracy_score(y_test_without_one_hot,y_pred_stack_without_one_hot))

Confusion Matrix : 
 [[ 5378   823   420   242    54    28   469    74]
 [  888 12145    43   120    15    26    90   115]
 [  762    79  1377    52    62    14   197     3]
 [  351   219    37   639   121     1    34     7]
 [   68    36    67   127   281     7    52     0]
 [   59    43    47     6    14   120    90     1]
 [  635    73   140    33    53    60  1482    12]
 [  110   191     7     3     1     5    17    41]]
Accuracy on test set:    0.7461238962664256


In [27]:
stacked_model.save("Final_Stacked_Generalization_ViT_and_VGG_Done_by_suabsh.h5")

In [ ]:
import tensorflow as tf
from transformers import ViTFeatureExtractor, TFViTModel

# Define or import your custom layers here
base_model = TFViTModel.from_pretrained("google/vit-base-patch16-224-in21k")

loaded_model = tf.keras.models.load_model("Final_Stacked_Generalization_ViT_and_VGG_Done_by_suabsh.h5", custom_objects={"TFViTModel": base_model.__class__})


In [30]:
loaded_model.summary()

Model: "functional_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
ensemble_2_input_1 (InputLayer) [(None, 224, 224, 3) 0                                            
__________________________________________________________________________________________________
ensemble_2_block1_conv1 (Conv2D (None, 224, 224, 64) 1792        ensemble_2_input_1[0][0]         
__________________________________________________________________________________________________
ensemble_2_block1_conv2 (Conv2D (None, 224, 224, 64) 36928       ensemble_2_block1_conv1[0][0]    
__________________________________________________________________________________________________
ensemble_2_block1_pool (MaxPool (None, 112, 112, 64) 0           ensemble_2_block1_conv2[0][0]    
_______________________________________________________________________________________