In [1]:
import os
os.chdir('/home/t326h379/AffectNet-8Labels/train_set/train_set/annotations/')

In [2]:
import tensorflow as tf
from transformers import ViTFeatureExtractor, TFViTModel

# Define or import your custom layers here
base_model = TFViTModel.from_pretrained("google/vit-base-patch16-224-in21k")

# Load the model with custom objects
loaded_model = tf.keras.models.load_model("VIT_KritikaSingh.h5", custom_objects={"TFViTModel": base_model.__class__})

2025-02-07 13:57:48.293861: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
All PyTorch model weights were used when initializing TFViTModel.

All the weights of TFViTModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFViTModel for predictions without further training.


In [4]:
loaded_model.summary()

Model: "functional_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 permute (Permute)           (None, 3, 224, 224)       0         
                                                                 
 vit (TFViTMainLayer)        TFBaseModelOutputWithPoo  86389248  
                             ling(last_hidden_state=(            
                             None, 197, 768),                    
                              pooler_output=(None, 76            
                             8),                                 
                              hidden_states=None, att            
                             entions=None)                       
                                                                 
 tf_op_layer_strided_slice (  (None, 768)             

# Load AffectNet Independent Test Dataset

In [1]:
import glob
import cv2
import time

# Record the starting time
start_time = time.time()

images = [cv2.imread(file) for file in glob.glob("/home/t326h379/AffectNet-8Labels/val_set/images/*.jpg")]

# Record the end time
end_time = time.time()

# Calculate the elapsed time
elapsed_time = end_time - start_time

# Print or use the elapsed time as needed
print(f"Execution time: {elapsed_time} seconds")

Execution time: 111.57019329071045 seconds


In [2]:
len(images)

3999

In [3]:
import numpy as np

# Record the starting time
start_time = time.time()

val_images_images = np.array(images)

# Record the end time
end_time = time.time()

# Calculate the elapsed time
elapsed_time = end_time - start_time

# Print or use the elapsed time as needed
print(f"Execution time: {elapsed_time} seconds")

Execution time: 0.16256093978881836 seconds


In [18]:
import glob

IMAGE_DIR = "/home/t326h379/AffectNet-8Labels/val_set/images"

for image_file_path in glob.glob(f"{IMAGE_DIR}/*.jpg"):
    print(f"Processing {image_file_path}")

Processing /home/t326h379/AffectNet-8Labels/val_set/images/1990.jpg
Processing /home/t326h379/AffectNet-8Labels/val_set/images/1245.jpg
Processing /home/t326h379/AffectNet-8Labels/val_set/images/4969.jpg
Processing /home/t326h379/AffectNet-8Labels/val_set/images/302.jpg
Processing /home/t326h379/AffectNet-8Labels/val_set/images/763.jpg
Processing /home/t326h379/AffectNet-8Labels/val_set/images/1183.jpg
Processing /home/t326h379/AffectNet-8Labels/val_set/images/1624.jpg
Processing /home/t326h379/AffectNet-8Labels/val_set/images/63.jpg
Processing /home/t326h379/AffectNet-8Labels/val_set/images/2731.jpg
Processing /home/t326h379/AffectNet-8Labels/val_set/images/3607.jpg
Processing /home/t326h379/AffectNet-8Labels/val_set/images/2047.jpg
Processing /home/t326h379/AffectNet-8Labels/val_set/images/1152.jpg
Processing /home/t326h379/AffectNet-8Labels/val_set/images/2854.jpg
Processing /home/t326h379/AffectNet-8Labels/val_set/images/2426.jpg
Processing /home/t326h379/AffectNet-8Labels/val_set/

In [4]:
val_images_images.shape

(3999, 224, 224, 3)

In [5]:
val_images = [file.split("/")[-1] for file in glob.glob("/home/t326h379/AffectNet-8Labels/val_set/images/*.jpg")]

In [6]:
val_images[-1]

'5125.jpg'

In [7]:
import glob
import os
os.chdir('/home/t326h379/AffectNet-8Labels/val_set/annotations/')
val_exp_file_count =[]
for name in glob.glob('*.npy'):
    a = name.split("_")
    if a[1].startswith("exp"):
        val_exp_file_count.append(name)

In [8]:
annotation_files_number_val = set()
for i in range(len(val_exp_file_count)):
    val_exp = val_exp_file_count[i].split("_")
    annotation_files_number_val.add(val_exp[0])

In [9]:
import pickle

with open('Kritika_AffectNet_Val.pickle', 'rb') as handle:
    a = pickle.load(handle)

In [33]:
a.get('1020')

array(6)

In [34]:
a

{'4100': array(6),
 '1656': array(6),
 '3270': array(7),
 '270': array(6),
 '2686': array(0),
 '495': array(1),
 '2229': array(7),
 '2063': array(4),
 '4971': array(2),
 '1164': array(7),
 '4478': array(5),
 '1915': array(5),
 '2751': array(5),
 '3542': array(4),
 '542': array(6),
 '708': array(6),
 '3708': array(1),
 '1209': array(4),
 '1043': array(1),
 '4715': array(2),
 '2093': array(6),
 '3465': array(6),
 '465': array(1),
 '1832': array(1),
 '3280': array(1),
 '280': array(0),
 '1771': array(6),
 '4027': array(2),
 '5234': array(3),
 '1194': array(5),
 '2144': array(4),
 '3357': array(1),
 '357': array(1),
 '2672': array(7),
 '3284': array(5),
 '2438': array(6),
 '2097': array(2),
 '3461': array(6),
 '119': array(0),
 '3119': array(5),
 '3353': array(6),
 '353': array(5),
 '2140': array(3),
 '5230': array(6),
 '3968': array(2),
 '968': array(4),
 '1190': array(5),
 '4269': array(5),
 '4023': array(0),
 '3491': array(1),
 '491': array(3),
 '4975': array(4),
 '2067': array(2),
 '16

In [10]:
y_val = []

for i in range(len(val_images)):
    
    y_val.append(int(a[val_images[i].split(".")[0]]))

In [15]:
y_val = np.array(y_val)

In [16]:
y_val.shape

(3999,)

In [17]:
val_images_images.shape

(3999, 224, 224, 3)

In [19]:
X_test_float32 = val_images_images.astype(np.float32) / 255.0

In [21]:
X_test_float32.shape

(3999, 224, 224, 3)

In [22]:
X_test_float32

array([[[[0.        , 0.        , 0.00392157],
         [0.        , 0.        , 0.00392157],
         [0.        , 0.        , 0.00392157],
         ...,
         [0.00784314, 0.00784314, 0.00784314],
         [0.00784314, 0.00784314, 0.00784314],
         [0.00784314, 0.00784314, 0.00784314]],

        [[0.        , 0.        , 0.00392157],
         [0.        , 0.        , 0.00392157],
         [0.        , 0.        , 0.00392157],
         ...,
         [0.00784314, 0.00784314, 0.00784314],
         [0.00784314, 0.00784314, 0.00784314],
         [0.00784314, 0.00784314, 0.00784314]],

        [[0.        , 0.        , 0.00392157],
         [0.        , 0.        , 0.00392157],
         [0.        , 0.        , 0.00392157],
         ...,
         [0.00784314, 0.00784314, 0.00784314],
         [0.00784314, 0.00784314, 0.00784314],
         [0.00784314, 0.00784314, 0.00784314]],

        ...,

        [[0.03137255, 0.00784314, 0.02745098],
         [0.02745098, 0.00392157, 0.02352941]

In [23]:
y_pred_vit = loaded_model.predict(X_test_float32)

125/125 [==============================] - 151s 1s/step


In [24]:
y_pred_vit_without_one_hot = np.argmax(y_pred_vit, axis=1)

In [25]:
from sklearn.metrics import matthews_corrcoef
from sklearn.metrics import confusion_matrix
from sklearn.metrics import *

In [26]:
print("Matthews Correlation : ",matthews_corrcoef(y_val, y_pred_vit_without_one_hot))
print("Confusion Matrix : \n",confusion_matrix(y_val, y_pred_vit_without_one_hot))
print("Accuracy on test set:   ",accuracy_score(y_val,y_pred_vit_without_one_hot))

Matthews Correlation :  0.45789730659577743
Confusion Matrix : 
 [[371  62  22  13   3   1  18  10]
 [ 21 466   2   5   0   1   1   4]
 [138  19 288   8  13   7  26   1]
 [121  88  24 202  54   2   7   2]
 [ 68  22  47  67 255   9  32   0]
 [ 97  62  52  12  20 150 106   1]
 [141  26  30  15  11   6 266   5]
 [151 263   8   4   2   6  17  48]]
Accuracy on test set:    0.5116279069767442
